### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by zzy0428** [MendelXu/SAN#21]
Hi,
I am trying to train the model and got following error 
Do you have any solution or comments?

![Weixin Image_20230909233832](https://github.com/MendelXu/SAN/assets/92824665/6368828b-2406-4b57-b007-4b2e4cf8e651)

**Comment by MendelXu** [comment]
It is caused by the newest detectron2 code. I have fixed it in https://github.com/MendelXu/SAN/commit/37171766dfa992276d28bac7c4b6c7e20d91ae7e. You can run the `install.sh` to reinstall the detectron2 package.

**Comment by zzy0428** [comment]
@MendelXu The latest version of detectron2 is 0.6. The issue still exists out there after reinstalling the detectron2 package.

**Comment by zzy0428** [comment]
Solved and thank you!
